# Makefile para Python (compatible con Windows y Linux)

# Nombre del archivo principal
TARGET = main.py

# Objetivo predeterminado
all: run

# Regla para ejecutar el script
run:
	python3 $(TARGET)

# Regla para limpiar archivos temporales
clean:
	rm -rf __pycache__

.PHONY: all run clean
