var searchData=
[
  ['manejo_20de_20excepciones_20en_20c_0',['&lt;em&gt;&lt;strong&gt;4. Manejo de Excepciones:&lt;/strong&gt;&lt;/em&gt; Describa los bloques &lt;strong&gt;try&lt;/strong&gt;, &lt;strong&gt;catch&lt;/strong&gt; y &lt;strong&gt;throw&lt;/strong&gt; y como se utilizan para el manejo de excepciones en C++.',['../md__r_e_a_d_m_e.html#autotoc_md7',1,'']]],
  ['manejo_20de_20excepciones_20y_20por_20que_20es_20importante_20considerarla_20al_20disenar_20software_1',['&lt;em&gt;&lt;strong&gt;6. Politica de Manejo de Excepciones:&lt;/strong&gt;&lt;/em&gt; ¿Que es una polıtica de manejo de excepciones y por que es importante considerarla al disenar software?',['../md__r_e_a_d_m_e.html#autotoc_md9',1,'']]],
  ['manejo_20de_20excepciones_3a_20strong_20em_20¿que_20es_20una_20polıtica_20de_20manejo_20de_20excepciones_20y_20por_20que_20es_20importante_20considerarla_20al_20disenar_20software_2',['&lt;em&gt;&lt;strong&gt;6. Politica de Manejo de Excepciones:&lt;/strong&gt;&lt;/em&gt; ¿Que es una polıtica de manejo de excepciones y por que es importante considerarla al disenar software?',['../md__r_e_a_d_m_e.html#autotoc_md9',1,'']]],
  ['manejo_20de_20excepciones_3a_20strong_20em_20describa_20los_20bloques_20strong_20try_20strong_20strong_20catch_20strong_20y_20strong_20throw_20strong_20y_20como_20se_20utilizan_20para_20el_20manejo_20de_20excepciones_20en_20c_3',['&lt;em&gt;&lt;strong&gt;4. Manejo de Excepciones:&lt;/strong&gt;&lt;/em&gt; Describa los bloques &lt;strong&gt;try&lt;/strong&gt;, &lt;strong&gt;catch&lt;/strong&gt; y &lt;strong&gt;throw&lt;/strong&gt; y como se utilizan para el manejo de excepciones en C++.',['../md__r_e_a_d_m_e.html#autotoc_md7',1,'']]],
  ['menos_20tres_20algoritmos_20de_20la_20stl_20y_20describa_20sus_20funciones_20basicas_4',['&lt;em&gt;&lt;strong&gt;10. Algoritmos STL:&lt;/strong&gt;&lt;/em&gt; Proporcione ejemplos de al menos tres algoritmos de la STL y describa sus funciones basicas.',['../md__r_e_a_d_m_e.html#autotoc_md14',1,'']]],
  ['menos_20tres_20caracteres_20especiales_20comunmente_20utilizados_20en_20expresiones_20regulares_20y_20describa_20sus_20funciones_5',['&lt;em&gt;&lt;strong&gt;13. Caracteres Especiales:&lt;/strong&gt;&lt;/em&gt; Enumere al menos tres caracteres especiales comunmente utilizados en expresiones regulares y describa sus funciones.',['../md__r_e_a_d_m_e.html#autotoc_md18',1,'']]],
  ['menos_20tres_20excepciones_20estandar_20proporcionadas_20por_20c_20y_20proporciona_20ejemplos_20de_20situaciones_20en_20las_20que_20podrıan_20ser_20utiles_6',['&lt;em&gt;&lt;strong&gt;5. Excepciones Estandar:&lt;/strong&gt;&lt;/em&gt; Nombre al menos tres excepciones estandar proporcionadas por C++ y proporciona ejemplos de situaciones en las que podrıan ser utiles.',['../md__r_e_a_d_m_e.html#autotoc_md8',1,'']]]
];
