var searchData=
[
  ['un_20algoritmo_20personalizado_20con_20la_20stl_0',['&lt;em&gt;&lt;strong&gt;11. Algoritmos Personalizados:&lt;/strong&gt;&lt;/em&gt; ¿Como podria utilizar un algoritmo personalizado con la STL?',['../md__r_e_a_d_m_e.html#autotoc_md15',1,'']]],
  ['un_20ejemplo_1',['&lt;em&gt;&lt;strong&gt;14.  Uso de Expresiones Regulares en C++:&lt;/strong&gt;&lt;/em&gt; ¿Como se utilizan las expresiones regulares en C++? Proporciona un ejemplo.',['../md__r_e_a_d_m_e.html#autotoc_md19',1,'']]],
  ['un_20ejemplo_20simple_2',['Un ejemplo simple',['../md__r_e_a_d_m_e.html#autotoc_md3',1,'&lt;em&gt;&lt;strong&gt;1. Definicion de Templates:&lt;/strong&gt;&lt;/em&gt; Explique el concepto de templates en C++ y proporcione un ejemplo simple.'],['../md__r_e_a_d_m_e.html#autotoc_md17',1,'&lt;em&gt;&lt;strong&gt;12. Definicion de Expresiones Regulares:&lt;/strong&gt;&lt;/em&gt;. ¿Defina que son las expresiones regulares y proporcione un ejemplo simple.']]],
  ['una_20polıtica_20de_20manejo_20de_20excepciones_20y_20por_20que_20es_20importante_20considerarla_20al_20disenar_20software_3',['&lt;em&gt;&lt;strong&gt;6. Politica de Manejo de Excepciones:&lt;/strong&gt;&lt;/em&gt; ¿Que es una polıtica de manejo de excepciones y por que es importante considerarla al disenar software?',['../md__r_e_a_d_m_e.html#autotoc_md9',1,'']]],
  ['uno_4',['&lt;em&gt;&lt;strong&gt;8. Contenedores STL:&lt;/strong&gt;&lt;/em&gt; Nombre cinco contenedores diferentes de la STL y explique brevemente en que situaciones serıa apropiado usar cada uno.',['../md__r_e_a_d_m_e.html#autotoc_md12',1,'']]],
  ['usar_20cada_20uno_5',['&lt;em&gt;&lt;strong&gt;8. Contenedores STL:&lt;/strong&gt;&lt;/em&gt; Nombre cinco contenedores diferentes de la STL y explique brevemente en que situaciones serıa apropiado usar cada uno.',['../md__r_e_a_d_m_e.html#autotoc_md12',1,'']]],
  ['uso_20de_20expresiones_20regulares_20en_20c_20_3a_20strong_20em_20¿como_20se_20utilizan_20las_20expresiones_20regulares_20en_20c_20proporciona_20un_20ejemplo_6',['&lt;em&gt;&lt;strong&gt;14.  Uso de Expresiones Regulares en C++:&lt;/strong&gt;&lt;/em&gt; ¿Como se utilizan las expresiones regulares en C++? Proporciona un ejemplo.',['../md__r_e_a_d_m_e.html#autotoc_md19',1,'']]],
  ['utiles_7',['&lt;em&gt;&lt;strong&gt;5. Excepciones Estandar:&lt;/strong&gt;&lt;/em&gt; Nombre al menos tres excepciones estandar proporcionadas por C++ y proporciona ejemplos de situaciones en las que podrıan ser utiles.',['../md__r_e_a_d_m_e.html#autotoc_md8',1,'']]],
  ['utiles_20para_20la_20validacion_20de_20patrones_20en_20cadenas_20de_20texto_8',['&lt;em&gt;&lt;strong&gt;15. Validacion de Patrones:&lt;/strong&gt;&lt;/em&gt; ¿Por que las expresiones regulares son utiles para la validacion de patrones en cadenas de texto?',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]],
  ['utiliza_20en_20c_9',['&lt;em&gt;&lt;strong&gt;7. Noexcept:&lt;/strong&gt;&lt;/em&gt; Explica el proposito de la palabra clave noexcept y como se utiliza en C++.',['../md__r_e_a_d_m_e.html#autotoc_md10',1,'']]],
  ['utilizados_20en_20expresiones_20regulares_20y_20describa_20sus_20funciones_10',['&lt;em&gt;&lt;strong&gt;13. Caracteres Especiales:&lt;/strong&gt;&lt;/em&gt; Enumere al menos tres caracteres especiales comunmente utilizados en expresiones regulares y describa sus funciones.',['../md__r_e_a_d_m_e.html#autotoc_md18',1,'']]],
  ['utilizan_20las_20expresiones_20regulares_20en_20c_20proporciona_20un_20ejemplo_11',['&lt;em&gt;&lt;strong&gt;14.  Uso de Expresiones Regulares en C++:&lt;/strong&gt;&lt;/em&gt; ¿Como se utilizan las expresiones regulares en C++? Proporciona un ejemplo.',['../md__r_e_a_d_m_e.html#autotoc_md19',1,'']]],
  ['utilizan_20para_20acceder_20a_20elementos_20en_20contenedores_12',['&lt;em&gt;&lt;strong&gt;9. Iteradores en STL:&lt;/strong&gt;&lt;/em&gt; Explique el concepto de iteradores en la STL y como se utilizan para acceder a elementos en contenedores.',['../md__r_e_a_d_m_e.html#autotoc_md13',1,'']]],
  ['utilizan_20para_20el_20manejo_20de_20excepciones_20en_20c_13',['&lt;em&gt;&lt;strong&gt;4. Manejo de Excepciones:&lt;/strong&gt;&lt;/em&gt; Describa los bloques &lt;strong&gt;try&lt;/strong&gt;, &lt;strong&gt;catch&lt;/strong&gt; y &lt;strong&gt;throw&lt;/strong&gt; y como se utilizan para el manejo de excepciones en C++.',['../md__r_e_a_d_m_e.html#autotoc_md7',1,'']]],
  ['utilizar_20plantillas_20en_20la_20definicion_20de_20clases_20en_20c_14',['&lt;em&gt;&lt;strong&gt;3. Plantillas de Clases:&lt;/strong&gt;&lt;/em&gt;  Explique como se pueden utilizar plantillas en la definicion de clases en C++.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['utilizar_20un_20algoritmo_20personalizado_20con_20la_20stl_15',['&lt;em&gt;&lt;strong&gt;11. Algoritmos Personalizados:&lt;/strong&gt;&lt;/em&gt; ¿Como podria utilizar un algoritmo personalizado con la STL?',['../md__r_e_a_d_m_e.html#autotoc_md15',1,'']]]
];
