var searchData=
[
  ['a_20elementos_20en_20contenedores_0',['&lt;em&gt;&lt;strong&gt;9. Iteradores en STL:&lt;/strong&gt;&lt;/em&gt; Explique el concepto de iteradores en la STL y como se utilizan para acceder a elementos en contenedores.',['../md__r_e_a_d_m_e.html#autotoc_md13',1,'']]],
  ['acceder_20a_20elementos_20en_20contenedores_1',['&lt;em&gt;&lt;strong&gt;9. Iteradores en STL:&lt;/strong&gt;&lt;/em&gt; Explique el concepto de iteradores en la STL y como se utilizan para acceder a elementos en contenedores.',['../md__r_e_a_d_m_e.html#autotoc_md13',1,'']]],
  ['al_20disenar_20software_2',['&lt;em&gt;&lt;strong&gt;6. Politica de Manejo de Excepciones:&lt;/strong&gt;&lt;/em&gt; ¿Que es una polıtica de manejo de excepciones y por que es importante considerarla al disenar software?',['../md__r_e_a_d_m_e.html#autotoc_md9',1,'']]],
  ['al_20menos_20tres_20algoritmos_20de_20la_20stl_20y_20describa_20sus_20funciones_20basicas_3',['&lt;em&gt;&lt;strong&gt;10. Algoritmos STL:&lt;/strong&gt;&lt;/em&gt; Proporcione ejemplos de al menos tres algoritmos de la STL y describa sus funciones basicas.',['../md__r_e_a_d_m_e.html#autotoc_md14',1,'']]],
  ['al_20menos_20tres_20caracteres_20especiales_20comunmente_20utilizados_20en_20expresiones_20regulares_20y_20describa_20sus_20funciones_4',['&lt;em&gt;&lt;strong&gt;13. Caracteres Especiales:&lt;/strong&gt;&lt;/em&gt; Enumere al menos tres caracteres especiales comunmente utilizados en expresiones regulares y describa sus funciones.',['../md__r_e_a_d_m_e.html#autotoc_md18',1,'']]],
  ['al_20menos_20tres_20excepciones_20estandar_20proporcionadas_20por_20c_20y_20proporciona_20ejemplos_20de_20situaciones_20en_20las_20que_20podrıan_20ser_20utiles_5',['&lt;em&gt;&lt;strong&gt;5. Excepciones Estandar:&lt;/strong&gt;&lt;/em&gt; Nombre al menos tres excepciones estandar proporcionadas por C++ y proporciona ejemplos de situaciones en las que podrıan ser utiles.',['../md__r_e_a_d_m_e.html#autotoc_md8',1,'']]],
  ['algoritmo_20personalizado_20con_20la_20stl_6',['&lt;em&gt;&lt;strong&gt;11. Algoritmos Personalizados:&lt;/strong&gt;&lt;/em&gt; ¿Como podria utilizar un algoritmo personalizado con la STL?',['../md__r_e_a_d_m_e.html#autotoc_md15',1,'']]],
  ['algoritmos_20de_20la_20stl_20y_20describa_20sus_20funciones_20basicas_7',['&lt;em&gt;&lt;strong&gt;10. Algoritmos STL:&lt;/strong&gt;&lt;/em&gt; Proporcione ejemplos de al menos tres algoritmos de la STL y describa sus funciones basicas.',['../md__r_e_a_d_m_e.html#autotoc_md14',1,'']]],
  ['algoritmos_20personalizados_3a_20strong_20em_20¿como_20podria_20utilizar_20un_20algoritmo_20personalizado_20con_20la_20stl_8',['&lt;em&gt;&lt;strong&gt;11. Algoritmos Personalizados:&lt;/strong&gt;&lt;/em&gt; ¿Como podria utilizar un algoritmo personalizado con la STL?',['../md__r_e_a_d_m_e.html#autotoc_md15',1,'']]],
  ['algoritmos_20stl_3a_20strong_20em_20proporcione_20ejemplos_20de_20al_20menos_20tres_20algoritmos_20de_20la_20stl_20y_20describa_20sus_20funciones_20basicas_9',['&lt;em&gt;&lt;strong&gt;10. Algoritmos STL:&lt;/strong&gt;&lt;/em&gt; Proporcione ejemplos de al menos tres algoritmos de la STL y describa sus funciones basicas.',['../md__r_e_a_d_m_e.html#autotoc_md14',1,'']]],
  ['apropiado_20usar_20cada_20uno_10',['&lt;em&gt;&lt;strong&gt;8. Contenedores STL:&lt;/strong&gt;&lt;/em&gt; Nombre cinco contenedores diferentes de la STL y explique brevemente en que situaciones serıa apropiado usar cada uno.',['../md__r_e_a_d_m_e.html#autotoc_md12',1,'']]]
];
