var searchData=
[
  ['y_20como_20se_20utiliza_20en_20c_0',['&lt;em&gt;&lt;strong&gt;7. Noexcept:&lt;/strong&gt;&lt;/em&gt; Explica el proposito de la palabra clave noexcept y como se utiliza en C++.',['../md__r_e_a_d_m_e.html#autotoc_md10',1,'']]],
  ['y_20como_20se_20utilizan_20para_20acceder_20a_20elementos_20en_20contenedores_1',['&lt;em&gt;&lt;strong&gt;9. Iteradores en STL:&lt;/strong&gt;&lt;/em&gt; Explique el concepto de iteradores en la STL y como se utilizan para acceder a elementos en contenedores.',['../md__r_e_a_d_m_e.html#autotoc_md13',1,'']]],
  ['y_20describa_20sus_20funciones_2',['&lt;em&gt;&lt;strong&gt;13. Caracteres Especiales:&lt;/strong&gt;&lt;/em&gt; Enumere al menos tres caracteres especiales comunmente utilizados en expresiones regulares y describa sus funciones.',['../md__r_e_a_d_m_e.html#autotoc_md18',1,'']]],
  ['y_20describa_20sus_20funciones_20basicas_3',['&lt;em&gt;&lt;strong&gt;10. Algoritmos STL:&lt;/strong&gt;&lt;/em&gt; Proporcione ejemplos de al menos tres algoritmos de la STL y describa sus funciones basicas.',['../md__r_e_a_d_m_e.html#autotoc_md14',1,'']]],
  ['y_20explique_20brevemente_20en_20que_20situaciones_20serıa_20apropiado_20usar_20cada_20uno_4',['&lt;em&gt;&lt;strong&gt;8. Contenedores STL:&lt;/strong&gt;&lt;/em&gt; Nombre cinco contenedores diferentes de la STL y explique brevemente en que situaciones serıa apropiado usar cada uno.',['../md__r_e_a_d_m_e.html#autotoc_md12',1,'']]],
  ['y_20por_20que_20es_20importante_20considerarla_20al_20disenar_20software_5',['&lt;em&gt;&lt;strong&gt;6. Politica de Manejo de Excepciones:&lt;/strong&gt;&lt;/em&gt; ¿Que es una polıtica de manejo de excepciones y por que es importante considerarla al disenar software?',['../md__r_e_a_d_m_e.html#autotoc_md9',1,'']]],
  ['y_20proporciona_20ejemplos_20de_20situaciones_20en_20las_20que_20podrıan_20ser_20utiles_6',['&lt;em&gt;&lt;strong&gt;5. Excepciones Estandar:&lt;/strong&gt;&lt;/em&gt; Nombre al menos tres excepciones estandar proporcionadas por C++ y proporciona ejemplos de situaciones en las que podrıan ser utiles.',['../md__r_e_a_d_m_e.html#autotoc_md8',1,'']]],
  ['y_20proporcione_20un_20ejemplo_20simple_7',['Y proporcione un ejemplo simple',['../md__r_e_a_d_m_e.html#autotoc_md3',1,'&lt;em&gt;&lt;strong&gt;1. Definicion de Templates:&lt;/strong&gt;&lt;/em&gt; Explique el concepto de templates en C++ y proporcione un ejemplo simple.'],['../md__r_e_a_d_m_e.html#autotoc_md17',1,'&lt;em&gt;&lt;strong&gt;12. Definicion de Expresiones Regulares:&lt;/strong&gt;&lt;/em&gt;. ¿Defina que son las expresiones regulares y proporcione un ejemplo simple.']]],
  ['y_20strong_20throw_20strong_20y_20como_20se_20utilizan_20para_20el_20manejo_20de_20excepciones_20en_20c_8',['&lt;em&gt;&lt;strong&gt;4. Manejo de Excepciones:&lt;/strong&gt;&lt;/em&gt; Describa los bloques &lt;strong&gt;try&lt;/strong&gt;, &lt;strong&gt;catch&lt;/strong&gt; y &lt;strong&gt;throw&lt;/strong&gt; y como se utilizan para el manejo de excepciones en C++.',['../md__r_e_a_d_m_e.html#autotoc_md7',1,'']]]
];
