var searchData=
[
  ['la_20definicion_20de_20clases_20en_20c_0',['&lt;em&gt;&lt;strong&gt;3. Plantillas de Clases:&lt;/strong&gt;&lt;/em&gt;  Explique como se pueden utilizar plantillas en la definicion de clases en C++.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['la_20palabra_20clave_20noexcept_20y_20como_20se_20utiliza_20en_20c_1',['&lt;em&gt;&lt;strong&gt;7. Noexcept:&lt;/strong&gt;&lt;/em&gt; Explica el proposito de la palabra clave noexcept y como se utiliza en C++.',['../md__r_e_a_d_m_e.html#autotoc_md10',1,'']]],
  ['la_20sobrecarga_20de_20funciones_20con_20plantillas_20en_20c_2',['&lt;em&gt;&lt;strong&gt;2. Sobrecarga de Plantillas:&lt;/strong&gt;&lt;/em&gt; ¿Como se realiza la sobrecarga de funciones con plantillas en C++?',['../md__r_e_a_d_m_e.html#autotoc_md4',1,'']]],
  ['la_20stl_3',['&lt;em&gt;&lt;strong&gt;11. Algoritmos Personalizados:&lt;/strong&gt;&lt;/em&gt; ¿Como podria utilizar un algoritmo personalizado con la STL?',['../md__r_e_a_d_m_e.html#autotoc_md15',1,'']]],
  ['la_20stl_20y_20como_20se_20utilizan_20para_20acceder_20a_20elementos_20en_20contenedores_4',['&lt;em&gt;&lt;strong&gt;9. Iteradores en STL:&lt;/strong&gt;&lt;/em&gt; Explique el concepto de iteradores en la STL y como se utilizan para acceder a elementos en contenedores.',['../md__r_e_a_d_m_e.html#autotoc_md13',1,'']]],
  ['la_20stl_20y_20describa_20sus_20funciones_20basicas_5',['&lt;em&gt;&lt;strong&gt;10. Algoritmos STL:&lt;/strong&gt;&lt;/em&gt; Proporcione ejemplos de al menos tres algoritmos de la STL y describa sus funciones basicas.',['../md__r_e_a_d_m_e.html#autotoc_md14',1,'']]],
  ['la_20stl_20y_20explique_20brevemente_20en_20que_20situaciones_20serıa_20apropiado_20usar_20cada_20uno_6',['&lt;em&gt;&lt;strong&gt;8. Contenedores STL:&lt;/strong&gt;&lt;/em&gt; Nombre cinco contenedores diferentes de la STL y explique brevemente en que situaciones serıa apropiado usar cada uno.',['../md__r_e_a_d_m_e.html#autotoc_md12',1,'']]],
  ['la_20validacion_20de_20patrones_20en_20cadenas_20de_20texto_7',['&lt;em&gt;&lt;strong&gt;15. Validacion de Patrones:&lt;/strong&gt;&lt;/em&gt; ¿Por que las expresiones regulares son utiles para la validacion de patrones en cadenas de texto?',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]],
  ['las_20expresiones_20regulares_20en_20c_20proporciona_20un_20ejemplo_8',['&lt;em&gt;&lt;strong&gt;14.  Uso de Expresiones Regulares en C++:&lt;/strong&gt;&lt;/em&gt; ¿Como se utilizan las expresiones regulares en C++? Proporciona un ejemplo.',['../md__r_e_a_d_m_e.html#autotoc_md19',1,'']]],
  ['las_20expresiones_20regulares_20son_20utiles_20para_20la_20validacion_20de_20patrones_20en_20cadenas_20de_20texto_9',['&lt;em&gt;&lt;strong&gt;15. Validacion de Patrones:&lt;/strong&gt;&lt;/em&gt; ¿Por que las expresiones regulares son utiles para la validacion de patrones en cadenas de texto?',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]],
  ['las_20expresiones_20regulares_20y_20proporcione_20un_20ejemplo_20simple_10',['&lt;em&gt;&lt;strong&gt;12. Definicion de Expresiones Regulares:&lt;/strong&gt;&lt;/em&gt;. ¿Defina que son las expresiones regulares y proporcione un ejemplo simple.',['../md__r_e_a_d_m_e.html#autotoc_md17',1,'']]],
  ['las_20que_20podrıan_20ser_20utiles_11',['&lt;em&gt;&lt;strong&gt;5. Excepciones Estandar:&lt;/strong&gt;&lt;/em&gt; Nombre al menos tres excepciones estandar proporcionadas por C++ y proporciona ejemplos de situaciones en las que podrıan ser utiles.',['../md__r_e_a_d_m_e.html#autotoc_md8',1,'']]],
  ['library_20_3a_12',['STL (Standard Template Library):',['../md__r_e_a_d_m_e.html#autotoc_md11',1,'']]],
  ['los_20bloques_20strong_20try_20strong_20strong_20catch_20strong_20y_20strong_20throw_20strong_20y_20como_20se_20utilizan_20para_20el_20manejo_20de_20excepciones_20en_20c_13',['&lt;em&gt;&lt;strong&gt;4. Manejo de Excepciones:&lt;/strong&gt;&lt;/em&gt; Describa los bloques &lt;strong&gt;try&lt;/strong&gt;, &lt;strong&gt;catch&lt;/strong&gt; y &lt;strong&gt;throw&lt;/strong&gt; y como se utilizan para el manejo de excepciones en C++.',['../md__r_e_a_d_m_e.html#autotoc_md7',1,'']]]
];
