var searchData=
[
  ['realiza_20la_20sobrecarga_20de_20funciones_20con_20plantillas_20en_20c_0',['&lt;em&gt;&lt;strong&gt;2. Sobrecarga de Plantillas:&lt;/strong&gt;&lt;/em&gt; ¿Como se realiza la sobrecarga de funciones con plantillas en C++?',['../md__r_e_a_d_m_e.html#autotoc_md4',1,'']]],
  ['regulares_20en_20c_20_3a_20strong_20em_20¿como_20se_20utilizan_20las_20expresiones_20regulares_20en_20c_20proporciona_20un_20ejemplo_1',['&lt;em&gt;&lt;strong&gt;14.  Uso de Expresiones Regulares en C++:&lt;/strong&gt;&lt;/em&gt; ¿Como se utilizan las expresiones regulares en C++? Proporciona un ejemplo.',['../md__r_e_a_d_m_e.html#autotoc_md19',1,'']]],
  ['regulares_20en_20c_20proporciona_20un_20ejemplo_2',['&lt;em&gt;&lt;strong&gt;14.  Uso de Expresiones Regulares en C++:&lt;/strong&gt;&lt;/em&gt; ¿Como se utilizan las expresiones regulares en C++? Proporciona un ejemplo.',['../md__r_e_a_d_m_e.html#autotoc_md19',1,'']]],
  ['regulares_20son_20utiles_20para_20la_20validacion_20de_20patrones_20en_20cadenas_20de_20texto_3',['&lt;em&gt;&lt;strong&gt;15. Validacion de Patrones:&lt;/strong&gt;&lt;/em&gt; ¿Por que las expresiones regulares son utiles para la validacion de patrones en cadenas de texto?',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]],
  ['regulares_20y_20describa_20sus_20funciones_4',['&lt;em&gt;&lt;strong&gt;13. Caracteres Especiales:&lt;/strong&gt;&lt;/em&gt; Enumere al menos tres caracteres especiales comunmente utilizados en expresiones regulares y describa sus funciones.',['../md__r_e_a_d_m_e.html#autotoc_md18',1,'']]],
  ['regulares_20y_20proporcione_20un_20ejemplo_20simple_5',['&lt;em&gt;&lt;strong&gt;12. Definicion de Expresiones Regulares:&lt;/strong&gt;&lt;/em&gt;. ¿Defina que son las expresiones regulares y proporcione un ejemplo simple.',['../md__r_e_a_d_m_e.html#autotoc_md17',1,'']]],
  ['regulares_3a_6',['Expresiones Regulares:',['../md__r_e_a_d_m_e.html#autotoc_md16',1,'']]],
  ['regulares_3a_20strong_20em_20¿defina_20que_20son_20las_20expresiones_20regulares_20y_20proporcione_20un_20ejemplo_20simple_7',['&lt;em&gt;&lt;strong&gt;12. Definicion de Expresiones Regulares:&lt;/strong&gt;&lt;/em&gt;. ¿Defina que son las expresiones regulares y proporcione un ejemplo simple.',['../md__r_e_a_d_m_e.html#autotoc_md17',1,'']]]
];
