var searchData=
[
  ['tarea_203_20ie_200207_20sebastián_20bonilla_20vega_20c01263_0',['Tarea 3,IE-0207,Sebastián Bonilla Vega, C01263.',['../md__r_e_a_d_m_e.html',1,'']]],
  ['template_20library_20_3a_1',['STL (Standard Template Library):',['../md__r_e_a_d_m_e.html#autotoc_md11',1,'']]],
  ['templates_20en_20c_20y_20proporcione_20un_20ejemplo_20simple_2',['&lt;em&gt;&lt;strong&gt;1. Definicion de Templates:&lt;/strong&gt;&lt;/em&gt; Explique el concepto de templates en C++ y proporcione un ejemplo simple.',['../md__r_e_a_d_m_e.html#autotoc_md3',1,'']]],
  ['templates_3a_3',['Templates:',['../md__r_e_a_d_m_e.html#autotoc_md2',1,'']]],
  ['templates_3a_20strong_20em_20explique_20el_20concepto_20de_20templates_20en_20c_20y_20proporcione_20un_20ejemplo_20simple_4',['&lt;em&gt;&lt;strong&gt;1. Definicion de Templates:&lt;/strong&gt;&lt;/em&gt; Explique el concepto de templates en C++ y proporcione un ejemplo simple.',['../md__r_e_a_d_m_e.html#autotoc_md3',1,'']]],
  ['texto_5',['&lt;em&gt;&lt;strong&gt;15. Validacion de Patrones:&lt;/strong&gt;&lt;/em&gt; ¿Por que las expresiones regulares son utiles para la validacion de patrones en cadenas de texto?',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]],
  ['throw_20strong_20y_20como_20se_20utilizan_20para_20el_20manejo_20de_20excepciones_20en_20c_6',['&lt;em&gt;&lt;strong&gt;4. Manejo de Excepciones:&lt;/strong&gt;&lt;/em&gt; Describa los bloques &lt;strong&gt;try&lt;/strong&gt;, &lt;strong&gt;catch&lt;/strong&gt; y &lt;strong&gt;throw&lt;/strong&gt; y como se utilizan para el manejo de excepciones en C++.',['../md__r_e_a_d_m_e.html#autotoc_md7',1,'']]],
  ['tres_20algoritmos_20de_20la_20stl_20y_20describa_20sus_20funciones_20basicas_7',['&lt;em&gt;&lt;strong&gt;10. Algoritmos STL:&lt;/strong&gt;&lt;/em&gt; Proporcione ejemplos de al menos tres algoritmos de la STL y describa sus funciones basicas.',['../md__r_e_a_d_m_e.html#autotoc_md14',1,'']]],
  ['tres_20caracteres_20especiales_20comunmente_20utilizados_20en_20expresiones_20regulares_20y_20describa_20sus_20funciones_8',['&lt;em&gt;&lt;strong&gt;13. Caracteres Especiales:&lt;/strong&gt;&lt;/em&gt; Enumere al menos tres caracteres especiales comunmente utilizados en expresiones regulares y describa sus funciones.',['../md__r_e_a_d_m_e.html#autotoc_md18',1,'']]],
  ['tres_20excepciones_20estandar_20proporcionadas_20por_20c_20y_20proporciona_20ejemplos_20de_20situaciones_20en_20las_20que_20podrıan_20ser_20utiles_9',['&lt;em&gt;&lt;strong&gt;5. Excepciones Estandar:&lt;/strong&gt;&lt;/em&gt; Nombre al menos tres excepciones estandar proporcionadas por C++ y proporciona ejemplos de situaciones en las que podrıan ser utiles.',['../md__r_e_a_d_m_e.html#autotoc_md8',1,'']]],
  ['try_20strong_20strong_20catch_20strong_20y_20strong_20throw_20strong_20y_20como_20se_20utilizan_20para_20el_20manejo_20de_20excepciones_20en_20c_10',['&lt;em&gt;&lt;strong&gt;4. Manejo de Excepciones:&lt;/strong&gt;&lt;/em&gt; Describa los bloques &lt;strong&gt;try&lt;/strong&gt;, &lt;strong&gt;catch&lt;/strong&gt; y &lt;strong&gt;throw&lt;/strong&gt; y como se utilizan para el manejo de excepciones en C++.',['../md__r_e_a_d_m_e.html#autotoc_md7',1,'']]]
];
