# Makefile para Python (compatible con Windows y Linux)

# Nombres de los archivos principales
TARGET1 = main.py

# Objetivo predeterminado
all: run

# Regla para ejecutar el primer script
run1:
	python $(TARGET1)

# Regla para ejecutar el segundo script


# Regla para limpiar archivos temporales
clean:
	rm -rf __pycache__ car_details_dataset.zip

.PHONY: all run1  clean
